unbind C-b
set -g prefix m-a
bind m-a send-prefix

set -g set-titles on
set -g focus-events on

set -g set-titles-string "#T"
set -g mouse on
set -g history-limit 5000000
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

set -g status-style "bg=#2e2e32,fg=#ffffff"

bind c new-window -c "#{pane_current_path}"
bind v split-window -c "#{pane_current_path}"
bind h split-window -h -c "#{pane_current_path}"
