position = "top"
height = 22
layer = "top"

#autohide = 7000
#start_hidden = false

[[start]]
type = "workspaces"
icon_size = 16

[[start]]
type = "focused"
icon_size = 16

[[end]]
type = "sys_info"
format = [
    "{cpu_percent}% ",
    "{memory_percent}% ",
    "{temp_c}°C   ",
]

[end.interval]
cpu = 1

[[end]]
type = "script"
mode = "poll"
interval = 2000
show_if = "command -v nvidia-smi"
cmd = "nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits | awk '{print $1\"% 󰢮\"}'"

[[end]]
type = "tray"
icon_size = 15

[[end]]
type = "volume"

[[end]]
type = "battery"
show_if = "ls /sys/class/power_supply/ | grep --quiet '^BAT'"
icon_size = 14

[[end]]
type = "network_manager"
icon_size = 16
types_blacklist = ["loopback"]

[[end]]
type = "clock"
format = "%A, %d %B, %H:%M"