import Pkg
Pkg.add("DifferentialEquations")
Pkg.add("PyCall")
Pkg.add("RCall")
Pkg.add("PyPlot")
Pkg.add("DelimitedFiles")
Pkg.add("Dierckx")
Pkg.add("LaTeXStrings")
Pkg.add("Distributed")
Pkg.add("DataFrames")
Pkg.add("CSV")
Pkg.add("Arrow")
Pkg.add("Plots")
Pkg.add("XGBoost")
Pkg.add("Clustering")
Pkg.add("Flux")
Pkg.add("Knet")
Pkg.add("ObjectDetector")
Pkg.add("TextAnalysis")
Pkg.add("AlphaZero")
Pkg.add("Turing")

#Pkg.add("")
